repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: parity
    url: https://paritytech.github.io/helm-charts/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

environments:
  default:
    values:
      - ./environments/dev/values.yaml
  development:
    values:
      - ./environments/dev/values.yaml
  staging:
    values:
      - ./environments/staging/values.yaml
  production:
    values:
      - ./environments/production/values.yaml

releases:
{{- range .Values.laosNodesInstances }}
  - name: {{ .name }}
    namespace: {{ $.Values.namespace }}
    createNamespace: false
    chart: parity/node
    version: 5.5.1
    installed: {{ .installed }}
    values:
      - image:
          repository: freeverseio/laos-node
          tag: {{ .nodeVersion }}
      - node:
          replicas: 1
          chain: {{ .chain }}
          command: "laos"
          isParachain: true
          telemetryUrls:
            - 'wss://telemetry.polkadot.io/submit 0'
          chainData:
            volumeSize: 256Gi
            pruning: false
          flags:
            - "--pruning=archive"
            - "--rpc-max-connections=500"
          perNodeServices:
            apiService:
              enabled: true
            setPublicAddressToExternalIp:
              enabled: true
              autodiscoveryFix: true
            paraP2pService:
              enabled: true
              type: NodePort
          collatorRelayChain:
            chainData:
              volumeSize: 512Gi
            flags:
              - --sync=fast
      {{- if and (hasKey . "setDnsPolicy") .setDnsPolicy }}
      - dnsPolicy: Default
      {{- end }}
{{- end }}

helmfiles:
  {{- range .Values.laosIndexerInstances }}
  - path: 'charts/laos-procesor/helmfile.yaml'
    values:
      - name: {{ .indexerName }}
      - namespace: {{ $.Values.namespace }}
      - imageTag: {{ requiredEnv "IMAGE_TAG" }}
      - postgresDb: {{ .postgresDb }}
      - postgresDbHost: {{ .postgresHost }}
      - postgresPasswordSecretKey: {{ .postgresPasswordSecretKey }}
      - postgresUser: {{ .postgresUser }}
      - postgresPort: {{ .postgresPort }}
      - rpcEndpointSecretKey: {{ .rpcEndpointSecretKey }}
      - startingBlock: {{ .startingBlock }}
      {{- if hasKey . "rpcRateLimit" }}
      - rpcRateLimit: {{ .rpcRateLimit }}
      {{- end }}
      {{- if hasKey . "pinataGatewayApiTokenSecretKey" }}
      - pinataGatewayApiTokenSecretKey: {{ .pinataGatewayApiTokenSecretKey }}
      {{- end }}
      - command: "process:prod:laos"
      - installed: {{ .installed }}
  {{- end }}

  {{- range .Values.ownershipIndexerInstances }}
  - path: 'charts/processor/helmfile.yaml'
    values:
      - name: {{ .indexerName }}
      - namespace: {{ $.Values.namespace }}
      - imageTag: {{ .chainName }}-{{ requiredEnv "IMAGE_TAG" }}
      - postgresDb: {{ .postgresDb }}
      - postgresDbHost: {{ .postgresHost }}
      - postgresPasswordSecretKey: {{ .postgresPasswordSecretKey }}
      - postgresUser: {{ .postgresUser }}
      - postgresPort: {{ .postgresPort }}
      {{- if hasKey . "gatewayEndpoint" }}
      - gatewayEndpoint: {{ .gatewayEndpoint }}
      {{- end }}
      - rpcEndpointSecretKey: {{ .rpcEndpointSecretKey }}
      - laosGlobalConsensus: {{ .laosGlobalConsensus }}
      - laosParachain: {{ .laosParachain }}
      - laosPalletInstance: {{ .laosPalletInstance }}
      - startingBlock: {{ .startingBlock }}
      - indexerOwnershipParseTraces: {{ .indexerParseTraces | quote }}
      {{- if hasKey . "maxBatchCallSizeOwnership" }}  
      - maxBatchCallSizeOwnership: {{ .maxBatchCallSizeOwnership }}
      {{- end }}
      {{- if hasKey . "pinataGatewayApiTokenSecretKey" }}
      - pinataGatewayApiTokenSecretKey: {{ .pinataGatewayApiTokenSecretKey }}
      {{- end }}
      - command: "process:prod:ownership_chain"
      - installed: {{ .installed }}
      {{- if hasKey . "rpcRateLimit" }}
      - rpcRateLimit: {{ .rpcRateLimit }}
      {{- end }}
      - installed: {{ .installed }}
{{- end }}

{{- range .Values.laosNodesInstances }}
{{- if hasKey . "nginxServiceUrl" }}
  - path: 'charts/nginx/helmfile.yaml'
    values:
      - namespace: {{ $.Values.namespace }}
      - name: nginx-{{ .name }}
      - nginxServiceUrl: {{ .nginxServiceUrl }}
      - installed: {{ .installed }}
{{- else }}
  - path: 'charts/nginx/helmfile.yaml'
    values:
      - namespace: {{ $.Values.namespace }}
      - name: nginx-{{ .name }}
      - nginxServiceUrl: ""
      - installed: false
{{- end }}
{{- end }}