repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: parity
    url: https://paritytech.github.io/helm-charts/

environments:
  default:
    values:
      - ./environments/dev/values.yaml
  development:
    values:
      - ./environments/dev/values.yaml
  staging:
    values:
      - ./environments/staging/values.yaml
  production:
    values:
      - ./environments/production/values.yaml

helmfiles:
  {{- range .Values.indexerInstances }}
  - path: 'charts/db/helmfile.yaml'
    values:
      - namespace: {{ $.Values.namespace }}
      - postgresDb: {{ .postgresDb }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      - pvcName: {{ .pvcName }}
      - podName: {{ .dbPodName }}
      - servicePort: {{ .servicePort }}
      - containerPort: {{ .containerPort }}
      - mountPath: {{ .mountPath }}
      - mountName: {{ .mountName }}
      - installed: {{ .installed }}
  - path: 'charts/processor/helmfile.yaml'
    values:
      - name: {{ .ownershipProcessor }}
      - namespace: {{ $.Values.namespace }}
      - imageTag: {{ requiredEnv "IMAGE_TAG" }}
      - postgresDb: {{ .postgresDb }}
      - postgresDbHost: {{ .dbPodName }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      - postgresPort: {{ .servicePort }}
      {{- if hasKey . "gatewayEndpoint" }}
      - gatewayEndpoint: {{ .gatewayEndpoint }}
      {{- end }}
      - rpcEndpointSecretKey: {{ .rpcEndpointSecretKey }}
      - laosGlobalConsensus: {{ .laosGlobalConsensus }}
      - laosParachain: {{ .laosParachain }}
      - laosPalletInstance: {{ .laosPalletInstance }}
      - startingBlockOwnership: {{ .startingBlockOwnership }}
      - startingBlockLaos: {{ .startingBlockLaos }}
      - indexerLaosRpcEndpointSecretKey: {{ .indexerLaosRpcEndpointSecretKey }}
      - indexerOwnershipParseTraces: {{ .indexerOwnershipParseTraces | quote }}
      {{- if hasKey . "maxBatchCallSizeOwnership" }}  
      - maxBatchCallSizeOwnership: {{ .maxBatchCallSizeOwnership }}
      {{- end }}
      {{- if hasKey . "rpcRateLimitOwnership" }}
      - rpcRateLimitOwnership: {{ .rpcRateLimitOwnership }}
      {{- end }}
      {{- if hasKey . "pinataGatewayApiTokenSecretKey" }}
      - pinataGatewayApiTokenSecretKey: {{ .pinataGatewayApiTokenSecretKey }}
      {{- end }}
      - command: "process:prod:ownership_chain"
      - installed: {{ .installed }}
  - path: 'charts/processor/helmfile.yaml'
    values:
      - name: {{ .laosProcessor }}
      - namespace: {{ $.Values.namespace }}
      - imageTag: {{ requiredEnv "IMAGE_TAG" }}
      - postgresDb: {{ .postgresDb }}
      - postgresDbHost: {{ .dbPodName }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      - postgresPort: {{ .servicePort }}
      - gatewayEndpoint: ""
      - rpcEndpointSecretKey: {{ .rpcEndpointSecretKey }}
      - laosGlobalConsensus: {{ .laosGlobalConsensus }}
      - laosParachain: {{ .laosParachain }}
      - laosPalletInstance: {{ .laosPalletInstance }}
      - startingBlockOwnership: {{ .startingBlockOwnership }}
      - startingBlockLaos: {{ .startingBlockLaos }}
      - command: "process:prod:laos"
      - indexerLaosRpcEndpointSecretKey: {{ .indexerLaosRpcEndpointSecretKey }}
      {{- if hasKey . "rpcRateLimit" }}
      - rpcRateLimit: {{ .rpcRateLimit }}
      {{- end }}
      {{- if hasKey . "pinataGatewayApiTokenSecretKey" }}
      - pinataGatewayApiTokenSecretKey: {{ .pinataGatewayApiTokenSecretKey }}
      {{- end }}
      - installed: {{ .installed }}
  - path: 'charts/api/helmfile.yaml'
    values:
      - name: {{ .apiProcessor }}
      - namespace: {{ $.Values.namespace }}
      - imageTag: {{ requiredEnv "IMAGE_TAG" }}
      - postgresDb: {{ .postgresDb }}
      - postgresDbHost: {{ .dbPodName }}
      - postgresPort: {{ .servicePort }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      {{- if hasKey . "host" }}
      - host: {{ .host }}
      {{- end }}
      - gqlPort: {{ .gqlPort }}
      - installed: {{ .installed }}
{{- end }}
{{- range .Values.laosNodesInstances }}
{{- if hasKey . "nginxServiceUrl" }}
  - path: 'charts/nginx/helmfile.yaml'
    values:
      - namespace: {{ $.Values.namespace }}
      - name: nginx-{{ .name }}
      - nginxServiceUrl: {{ .nginxServiceUrl }}
      - installed: {{ .installed }}
{{- else }}
  - path: 'charts/nginx/helmfile.yaml'
    values:
      - namespace: {{ $.Values.namespace }}
      - name: nginx-{{ .name }}
      - nginxServiceUrl: ""
      - installed: false
{{- end }}
{{- end }}

releases:
{{- range .Values.laosNodesInstances }}
  - name: {{ .name }}
    namespace: {{ $.Values.namespace }}
    createNamespace: false
    chart: parity/node
    version: 5.5.1
    installed: {{ .installed }}
    values:
      - image:
          repository: freeverseio/laos-node
          tag: {{ .nodeVersion }}
      - node:
          replicas: 1
          chain: {{ .chain }}
          command: "laos"
          isParachain: true
          telemetryUrls:
            - 'wss://telemetry.polkadot.io/submit 0'
          chainData:
            volumeSize: 256Gi
            pruning: false
          flags:
            - "--pruning=archive"
            - "--rpc-max-connections=500"
          perNodeServices:
            apiService:
              enabled: true
            setPublicAddressToExternalIp:
              enabled: true
              autodiscoveryFix: true
            paraP2pService:
              enabled: true
              type: NodePort
          collatorRelayChain:
            chainData:
              volumeSize: 512Gi
            flags:
              - --sync=fast
      {{- if and (hasKey . "setDnsPolicy") .setDnsPolicy }}
      - dnsPolicy: Default
      {{- end }}
{{- end }}
