repositories:
  - name: stable
    url: https://charts.helm.sh/stable

environments:
  default:
    values:
      - ./environments/dev/values.yaml
  development:
    values:
      - ./environments/dev/values.yaml
  staging:
    values:
      - ./environments/staging/values.yaml
  production:
    values:
      - ./environments/production/values.yaml

helmfiles:
  {{- range .Values.indexerInstances }}
  - path: 'charts/db/helmfile.yaml'
    values:
      - namespace: {{ $.Values.namespace }}
      - postgresDb: {{ .postgresDb }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      - pvcName: {{ .pvcName }}
      - podName: {{ .dbPodName }}
      - servicePort: {{ .servicePort }}
      - containerPort: {{ .containerPort }}
      - mountPath: {{ .mountPath }}
      - mountName: {{ .mountName }}
  - path: 'charts/processor/helmfile.yaml'
    values:
      - name: {{ .ownershipProcessor }}
      - namespace: {{ $.Values.namespace }}
      - imageTag: {{ requiredEnv "IMAGE_TAG" }}
      - postgresDb: {{ .postgresDb }}
      - postgresDbHost: {{ .dbPodName }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      - postgresPort: {{ .servicePort }}
      {{- if hasKey . "gatewayEndpoint" }}
      - gatewayEndpoint: {{ .gatewayEndpoint }}
      {{- end }}
      - rpcEndpointSecretKey: {{ .rpcEndpointSecretKey }}
      - laosGlobalConsensus: {{ .laosGlobalConsensus }}
      - laosParachain: {{ .laosParachain }}
      - laosPalletInstance: {{ .laosPalletInstance }}
      - startingBlockOwnership: {{ .startingBlockOwnership }}
      - startingBlockLaos: {{ .startingBlockLaos }}
      - indexerLaosRpcEndpointSecretKey: {{ .indexerLaosRpcEndpointSecretKey }}
      - indexerOwnershipParseTraces: {{ .indexerOwnershipParseTraces | quote }}
      {{- if hasKey . "maxBatchCallSizeOwnership" }}  
      - maxBatchCallSizeOwnership: {{ .maxBatchCallSizeOwnership }}
      {{- end }}
      {{- if hasKey . "rpcRateLimitOwnership" }}
      - rpcRateLimitOwnership: {{ .rpcRateLimitOwnership }}
      {{- end }}
      {{- if hasKey . "pinataGatewayApiTokenSecretKey" }}
      - pinataGatewayApiTokenSecretKey: {{ .pinataGatewayApiTokenSecretKey }}
      {{- end }}
      - command: "process:prod:ownership_chain"
  - path: 'charts/processor/helmfile.yaml'
    values:
      - name: {{ .laosProcessor }}
      - namespace: {{ $.Values.namespace }}
      - imageTag: {{ requiredEnv "IMAGE_TAG" }}
      - postgresDb: {{ .postgresDb }}
      - postgresDbHost: {{ .dbPodName }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      - postgresPort: {{ .servicePort }}
      - gatewayEndpoint: ""
      - rpcEndpointSecretKey: {{ .rpcEndpointSecretKey }}
      - laosGlobalConsensus: {{ .laosGlobalConsensus }}
      - laosParachain: {{ .laosParachain }}
      - laosPalletInstance: {{ .laosPalletInstance }}
      - startingBlockOwnership: {{ .startingBlockOwnership }}
      - startingBlockLaos: {{ .startingBlockLaos }}
      - command: "process:prod:laos"
      - indexerLaosRpcEndpointSecretKey: {{ .indexerLaosRpcEndpointSecretKey }}
      {{- if hasKey . "rpcRateLimit" }}
      - rpcRateLimit: {{ .rpcRateLimit }}
      {{- end }}
      {{- if hasKey . "pinataGatewayApiTokenSecretKey" }}
      - pinataGatewayApiTokenSecretKey: {{ .pinataGatewayApiTokenSecretKey }}
      {{- end }}
  - path: 'charts/api/helmfile.yaml'
    values:
      - name: {{ .apiProcessor }}
      - namespace: {{ $.Values.namespace }}
      - imageTag: {{ requiredEnv "IMAGE_TAG" }}
      - postgresDb: {{ .postgresDb }}
      - postgresDbHost: {{ .dbPodName }}
      - postgresPort: {{ .servicePort }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      - host: {{ .host }}
      - gqlPort: {{ .gqlPort }}
{{- end }}
  

