repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: false
  waitForJobs: true

namespace: laossigma-orion

releases:
  - name: public-node-1
    chart: parity/node
    version: 5.5.1
    values:
      - image:
          repository: freeverseio/laos-node
          tag: "v0.23.0"
      - node:
          replicas: 1
          chain: laos-sigma
          command: "laos"
          isParachain: true
          telemetryUrls:
            - 'wss://telemetry.polkadot.io/submit 0'
          chainData:
            volumeSize: 256Gi
            pruning: false
          flags:
            - "--pruning=archive"
            - "--rpc-max-connections=100"
          perNodeServices:
            apiService:
              enabled: true
            setPublicAddressToExternalIp:
              enabled: true
              autodiscoveryFix: true
            paraP2pService:
              enabled: true
              type: NodePort
          collatorRelayChain:
            chainData:
              volumeSize: 512Gi
            flags:
              - --sync=fast
      - ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
            nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
            nginx.ingress.kubernetes.io/auth-tls-error-page: "http://www.mysite.com/error-cert.html"
            nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
            nginx.ingress.kubernetes.io/websocket-services: "public-node-1"
            cert-manager.io/cluster-issuer: letsencrypt-freeverse
            nginx.ingress.kubernetes.io/limit-connections: "60"
            nginx.ingress.kubernetes.io/limit-rpm: "6000"
          rules:
          - host: rpc.orion-1.laossigma.laosnetwork.io
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: public-node-1
                    port:
                      name: websocket-rpc
          tls:
            - hosts:
              - rpc.orion-1.laossigma.laosnetwork.io
              secretName: public-node-1-tls
  - name: public-node-2
    chart: parity/node
    version: 5.5.1
    values:
      - image:
          repository: freeverseio/laos-node
          tag: "v0.23.0"
      - node:
          replicas: 1
          chain: laos-sigma
          command: "laos"
          isParachain: true
          telemetryUrls:
            - 'wss://telemetry.polkadot.io/submit 0'
          chainData:
            volumeSize: 256Gi
            pruning: false
          flags:
            - "--pruning=archive"
            - "--rpc-max-connections=100"
          perNodeServices:
            apiService:
              enabled: true
            setPublicAddressToExternalIp:
              enabled: true
              autodiscoveryFix: true
            paraP2pService:
              enabled: true
              type: NodePort
          collatorRelayChain:
            chainData:
              volumeSize: 512Gi
            flags:
              - --sync=fast
      - ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
            nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
            nginx.ingress.kubernetes.io/auth-tls-error-page: "http://www.mysite.com/error-cert.html"
            nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
            nginx.ingress.kubernetes.io/websocket-services: "public-node-2"
            cert-manager.io/cluster-issuer: letsencrypt-freeverse
            nginx.ingress.kubernetes.io/limit-connections: "60"
            nginx.ingress.kubernetes.io/limit-rpm: "6000"
          rules:
          - host: rpc.orion-2.laossigma.laosnetwork.io
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: public-node-2
                    port:
                      name: websocket-rpc
          tls:
            - hosts:
              - rpc.orion-2.laossigma.laosnetwork.io
              secretName: public-node-2-tls