apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: freeverseio/laos-indexer:{{ .Values.imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: '1'
            limits:
              memory: "2Gi"
              cpu: '2'
          env:
            - name: DB_NAME
              value: {{ .Values.postgresDb }}
            - name: DB_PORT
              value: {{ .Values.postgresPort | quote }}
            - name: DB_HOST
              value: {{ .Values.postgresDbHost }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: {{ .Values.postgresPasswordSecretKey }}
            - name: DB_USER
              value: {{ .Values.postgresUser }}
            {{- end }}
            - name: PRIVATE_IPFS_GATEWAY
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: indexerIpfsGateway
            - name: RPC_LAOS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: {{ .Values.rpcEndpointSecretKey }}
            - name: STARTING_BLOCK_LAOS
              value: {{ .Values.startingBlock | quote }}
            {{- if hasKey .Values "rpcRateLimit" }}
            - name: RPC_RATE_LIMIT
              value: {{ .Values.rpcRateLimit | quote }}
            {{- end }}
            {{- if hasKey .Values "pinataGatewayApiTokenSecretKey" }}
            - name: PRIVATE_IPFS_GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: {{ .Values.pinataGatewayApiTokenSecretKey | quote }}
            {{- end }}
          command: ["sqd", {{ .Values.command }}]
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - |
                BLOCKS_PER_SECOND=$(wget -qO- http://localhost:3000/metrics | grep 'sqd_processor_mapping_blocks_per_second' | awk '{print $2}')
                if [ -z "$BLOCKS_PER_SECOND" ]; then
                  echo "Metric not available. /metrics endpoint might not be accessible."
                  exit 1
                fi
                if (( $(echo "$BLOCKS_PER_SECOND < 1" | bc -l) )); then
                  echo "Processor stalled! Blocks per second is too low: $BLOCKS_PER_SECOND"
                  exit 1
                fi
                exit 0
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3