releases:
  - name: laos-indexer-btc-api-release
    namespace: '{{ .Values.namespace }}'
    createNamespace: false
    chart: .
    values:
      - imageTag: {{ .Values.imageTag }}
      - clientApiBtcHost: {{ .Values.clientApiBtcHost }}
      - postgresUser: {{ .Values.postgresUser }}
      - postgresHost: {{ .Values.postgresHost }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresPort: {{ .Values.postgresPort }}
      - postgresPasswordSecretKey: {{ .Values.postgresPasswordSecretKey }}
      
