namespace: indexers
laosIndexerInstances:
  - chainName: Mainnet # TODO make case insensitive
    indexerName: indexer-laos-mainnet
    postgresDb: indexerdb
    postgresPasswordSecretKey: indexerPostgresPassword
    postgresUser: indexer
    postgresHost: "pro-db-do-user-4813238-0.h.db.ondigitalocean.com"
    postgresPort: 25060
    startingBlock: "1"
    rpcEndpointSecretKey: "indexerLaosRpcEndpoint"
    # rpcRateLimit: 10
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken"
    installed: "true"
laosNodesInstances:
  - name: public-node-protostar
    nodeVersion: "v0.25.0"
    chain: "laos-sigma"
    installed: true
  - name: laos-node-protostar
    nodeVersion: "v0.25.0"
    chain: "laos"
    setDnsPolicy: true
    installed: true
ownershipIndexerInstances: []