namespace: protostar
rpcLaos: wss://rpc.laos.laosfoundation.io
indexerInstances:
  - dbPodName: indexer-db-polygon
    postgresDb: squid
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-1
    servicePort: 5432
    containerPort: 5432
    mountPath: /var/lib/postgresql/pvdata
    mountName: indexer-pvc
    ownershipProcessor: indexer-polygon-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/polygon-mainnet
    startingBlockOwnership: "61394132"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerPolygonRpcEndpoint"
    laosProcessor: indexer-laos-processor-polygon
    apiProcessor: indexer-laos-polygon-api
    host: polygon-indexer.laosnetwork.io
    gqlPort: 4000
    rpcRateLimit: 40
    # maxBatchCallSizeOwnership: 300
    # rpcRateLimitOwnership: 10
    # pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken"
    indexerLaosRpcEndpointSecretKey: "indexerLaosRpcEndpointA"
    indexerOwnershipParseTraces: "false"
    laosGlobalConsensus: "2"
    laosParachain: "3370"
    laosPalletInstance: "51"
  - dbPodName: indexer-db-ethereum
    postgresDb: squid-ethereum
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-ethereum-1
    servicePort: 5433
    containerPort: 5433
    mountPath: /var/lib/postgresql/pvdata2
    mountName: indexer-pvc-ethereum
    ownershipProcessor: indexer-ethereum-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/ethereum-mainnet
    startingBlockOwnership: "20673497"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerEthereumRpcEndpoint"
    laosProcessor: indexer-laos-processor-ethereum
    apiProcessor: indexer-laos-ethereum-api
    host: ethereum-indexer.laosnetwork.io
    gqlPort: 4000
    rpcRateLimit: 40
    # maxBatchCallSizeOwnership: 100
    # rpcRateLimitOwnership: 10
    # pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken"
    indexerLaosRpcEndpointSecretKey: "indexerLaosRpcEndpointA"
    indexerOwnershipParseTraces: "false"
    laosGlobalConsensus: "2"
    laosParachain: "3370"
    laosPalletInstance: "51"
  - dbPodName: indexer-db-hedera
    postgresDb: squid
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-hedera-1
    servicePort: 5432
    containerPort: 5432
    mountPath: /var/lib/postgresql/pvdata3
    mountName: indexer-pvc-hedera
    ownershipProcessor: indexer-hedera-processor
    startingBlockOwnership: "72113678"
    startingBlockLaos: "992886"
    rpcEndpointSecretKey: "indexerHederaRpcEndpoint"
    laosProcessor: indexer-laos-processor-hedera
    apiProcessor: indexer-laos-hedera-api
    host: hedera-indexer.laosnetwork.io
    gqlPort: 4000
    rpcRateLimit: 40
    # maxBatchCallSizeOwnership: 100
    # rpcRateLimitOwnership: 10
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken"
    indexerLaosRpcEndpointSecretKey: "indexerLaosRpcEndpointB"
    indexerOwnershipParseTraces: "false" 
    laosGlobalConsensus: "2"
    laosParachain: "3370"
    laosPalletInstance: "51"
laosNodesInstances:
  - name: laos-node-protostar
    nodeVersion: "v0.20.0"
    chain: "laos"
    setDnsPolicy: true
  - name: laos-node-protostar-1
    nodeVersion: "v0.22.0"
    chain: "laos"
    setDnsPolicy: true
