apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/app: {{ .Values.name }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}-metrics
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack-release
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 27.2.0
    chart: kube-prometheus-stack-27.2.0
    release: kube-prometheus-stack-release
spec:
  selector:
    matchLabels:
       app.kubernetes.io/app: {{ .Values.name }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
