releases:
  - name: {{ .Values.name }}-release
    namespace: '{{ .Values.namespace }}'
    createNamespace: false
    installed: {{ .Values.installed }}
    chart: .
    values:
      - name: {{ .Values.name }}
      - imageTag: {{ .Values.imageTag }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresDbHost: {{ .Values.postgresDbHost }}
      - postgresPasswordSecretKey: {{ .Values.postgresPasswordSecretKey }}
      - postgresUser: {{ .Values.postgresUser }}
      - postgresPort: {{ .Values.postgresPort }}
      - rpcEndpointSecretKey: {{ .Values.rpcEndpointSecretKey }}
      - startingBlock: {{ .Values.startingBlock }}      
      - command: {{ .Values.command }}
      {{- if hasKey .Values "rpcRateLimit" }}
      - rpcRateLimit: {{ .Values.rpcRateLimit }}
      {{- end }}
      {{- if hasKey .Values "pinataGatewayApiTokenSecretKey" }}
      - pinataGatewayApiTokenSecretKey: {{ .Values.pinataGatewayApiTokenSecretKey }}
      {{- end }}