version: 2.1

orbs:
  kube-orb: circleci/kubernetes@1.3.1
  helm: circleci/helm@3.0.2

parameters:
  imageTag:
    type: string
    default: latest

commands:
  install-helmfile:
    description: Install helmfile
    steps:
      - run:
          name: Install helmfile
          command: ./circleci-scripts/install-helmfile.sh

  checkout-app:
    description: Checkout app
    steps:
      - run:
          name: Checkout API
          command: |
            git clone git@github.com:freeverseio/laos-apis.git
            cd laos-apis
            git fetch origin feature/star-topology
            git checkout feature/star-topology

  get-image-tag:
    description: Get image tag
    steps:
      - run:
          name: Get image tag
          command: |
            git clone --no-checkout git@github.com:freeverseio/laos-apis.git
            cd laos-apis
            echo "Fetching image tag $IMAGE_TAG"
            git fetch origin $IMAGE_TAG
            git checkout $IMAGE_TAG
            echo "Using IMAGE_TAG=$IMAGE_TAG"
            export IMAGE_TAG=$IMAGE_TAG


  dockerize-and-push:
    parameters:
      image:
        type: string
      root:
        type: string
      chainName:
        type: string
        default: ""
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWD | docker login -u $DOCKER_ID --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            cd laos-apis
            IMAGE_TAG=$(git rev-parse HEAD)
            cd << parameters.root >>

            CHAIN_NAME_LOWER=$(echo "<< parameters.chainName >>" | tr '[:upper:]' '[:lower:]')

            if [ "$CHAIN_NAME_LOWER" != "" ]; then
              IMAGE_TAG="$CHAIN_NAME_LOWER-$IMAGE_TAG"
              BUILD_ARGS="--build-arg CHAIN_NAME=<< parameters.chainName >>"
            else
              BUILD_ARGS=""
            fi

            echo "Docker images for $IMAGE_TAG will be pushed"
            docker build $BUILD_ARGS -t << parameters.image >>:$IMAGE_TAG .
            docker push << parameters.image >>:$IMAGE_TAG

jobs:
  build-app:
    parameters:
      image:
        type: string
      root:
        type: string
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout-app
      - dockerize-and-push:
          image: << parameters.image >>
          root: << parameters.root >>

  build-indexer:
    parameters:
      image:
        type: string
      root:
        type: string
      chainName:
        type: string
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout-app
      - dockerize-and-push:
          image: << parameters.image >>
          root: << parameters.root >>
          chainName: << parameters.chainName >>

  deploy_to_cluster:
    parameters:
      environment:
        type: string
        default: development
      root:
        type: string
      imageTag:
        type: string
    description: Deploy to << parameters.environment >> environment
    docker:
      - image: cimg/deploy:2023.09
    steps:
      - checkout
      - kube-orb/install-kubectl:
          kubectl-version: 'v1.25.14'
      - when:
          condition:
            equal: [ development, << parameters.environment >> ]
          steps:
            - kube-orb/install-kubeconfig:
                kubeconfig: KUBECONFIG_INDEXERS_DATA
      - when:
          condition:
            equal: [ staging, << parameters.environment >> ]
          steps:
            - kube-orb/install-kubeconfig:
                kubeconfig: KUBECONFIG_PROTOSTAR_STG_DATA
      - helm/install_helm_client:
          version: v3.13.0
      - install-helmfile
      - run:
          name: Deploy to << parameters.environment >> environment
          command: |
            echo "Deploying to << parameters.environment >> environment"
            export IMAGE_TAG=<< parameters.imageTag >>
            git clone --no-checkout git@github.com:freeverseio/laos-apis.git
            cd laos-apis
            git fetch origin feature/star-topology
            git checkout feature/star-topology
            if [ "<< parameters.imageTag >>" = "latest" ]; then
              IMAGE_TAG=$(git rev-parse HEAD)
            fi
            echo "Fetching image tag $IMAGE_TAG"
            git fetch origin $IMAGE_TAG
            git checkout $IMAGE_TAG
            echo "Using IMAGE_TAG=$IMAGE_TAG"
            cd ..
            cd deployment
            cd << parameters.root >>
            helmfile sync --environment << parameters.environment >>

  deployment-test:
    parameters:
      root:
        type: string
      imageTag:
        type: string
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - helm/install_helm_client:
          version: v3.13.0
      - install-helmfile
      - run:
          name: Test Helmfile
          command: |
            echo "Helmfile tests passing"
            export IMAGE_TAG=<< parameters.imageTag >>
            git clone --no-checkout git@github.com:freeverseio/laos-apis.git
            cd laos-apis
            git fetch origin feature/star-topology
            git checkout feature/star-topology
            if [ "<< parameters.imageTag >>" = "latest" ]; then
              IMAGE_TAG=$(git rev-parse HEAD)
            fi
            echo "Fetching image tag $IMAGE_TAG"
            git fetch origin $IMAGE_TAG
            git checkout $IMAGE_TAG
            echo "Using IMAGE_TAG=$IMAGE_TAG"
            cd ..
            cd deployment
            cd << parameters.root >>
            helmfile lint
            echo "Deployment tests passed commit $IMAGE_TAG"


workflows:
  ci-workflow:
    jobs:
      - build-app:
          name: build-laos-indexer-api
          image: freeverseio/laos-indexer-api
          root: laos-indexer-api
          context: dockerhub

      - build-indexer:
          name: build-laos-indexer
          image: freeverseio/laos-indexer
          root: laos-indexer
          chainName: laos
          context: dockerhub
        
      - build-indexer:
          name: build-polygon-ownership-indexer
          image: freeverseio/laos-ownership-indexer
          root: laos-ownership-indexer
          chainName: Polygon
          context: dockerhub

      - build-indexer:
          name: build-ethereum-ownership-indexer
          image: freeverseio/laos-ownership-indexer
          root: laos-ownership-indexer
          chainName: Ethereum
          context: dockerhub

      - deployment-test:
          name: deployment-test-indexer
          root: indexer
          imageTag: << pipeline.parameters.imageTag >>

      - deployment-test:
          name: deployment-apis
          root: ./
          imageTag: << pipeline.parameters.imageTag >>

      - approval:
          type: approval
          name: approve-deploy-apis
          requires:
            - build-laos-indexer-api
          filters:
            branches:
              only:
                - main

      - approval:
          type: approval
          name: approve-deploy-apis-staging
          requires:
            - build-laos-indexer-api
          filters:
            branches:
              only:
                - main

      - approval:
          type: approval
          name: approve-deploy-indexer
          requires:
            - deployment-test-indexer
            - build-laos-indexer
            - build-ethereum-ownership-indexer
            - build-polygon-ownership-indexer
          filters:
            branches:
              only:
                - main
      
      - approval:
          type: approval
          name: approve-deploy-indexer-staging
          requires:
            - deployment-test-indexer
            - build-laos-indexer
            - build-ethereum-ownership-indexer
            - build-polygon-ownership-indexer
          filters:
            branches:
              only:
                - main


      - deploy_to_cluster:
          name: deploy-to-dev-api
          requires:
            - approve-deploy-apis
          environment: development
          root: ./
          imageTag: << pipeline.parameters.imageTag >>
          filters:
            branches:
              only:
                - main

      - deploy_to_cluster:
          name: deploy-to-dev-indexer
          requires:
            - deployment-test-indexer
            - approve-deploy-indexer
          environment: development
          root: indexer
          imageTag: << pipeline.parameters.imageTag >>
          filters:
            branches:
              only:
                - main

      - deploy_to_cluster:
          name: deploy-to-staging-api
          requires:
            - approve-deploy-apis-staging
          environment: staging
          root: ./
          imageTag: << pipeline.parameters.imageTag >>
          filters:
            branches:
              only:
                - main

      - deploy_to_cluster:
          name: deploy-to-staging-indexer
          requires:
            - deployment-test-indexer
            - approve-deploy-indexer-staging
          environment: staging
          root: indexer
          imageTag: << pipeline.parameters.imageTag >>
          filters:
            branches:
              only:
                - main
