apiVersion: apps/v1
kind: Deployment
metadata:
  name: laos-indexer-api
  labels:
    app.kubernetes.io/app: laos-indexer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: laos-indexer-api
  template:
    metadata:
      labels:
        app.kubernetes.io/app: laos-indexer-api
    spec:
      containers:
        - name: laos-indexer-api
          image: freeverseio/laos-indexer-api:{{ .Values.imageTag }}
          imagePullPolicy: Always
          volumeMounts:
            - name: db-certificate
              mountPath: "/app/data"
              readOnly: true
            - name: supported-chains
              mountPath: "/app/supported-chains/"
              readOnly: true
          resources:
            requests:
              memory: '256Mi'
              cpu: '1'
            limits:
              memory: '512Mi'
              cpu: '2'
          env:  
            - name: GQL_PORT
              value: "4001"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexers-private-config
                  key: {{ .Values.postgresPasswordSecretKey }}
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgresUser }}:$(POSTGRES_PASSWORD)@{{.Values.postgresHost}}:{{.Values.postgresPort}}/{{.Values.postgresDb}}?sslmode=require&sslrootcert=./data/ca-certificate.pem"            
            - name: SUPPORTED_CHAINS
              valueFrom:
                configMapKeyRef:
                  name: supported-chains
                  key: supported-chains.json
          ports:
            - containerPort: 4001
      volumes:
        - name: db-certificate
          secret:
            secretName: db-cert
        - name: supported-chains
          configMap:
            name: supported-chains