namespace: protostar
rpcLaos: wss://rpc.laossigma.laosfoundation.io
indexerInstances:
  - dbPodName: indexer-db-polygon
    postgresDb: squid
    postgresPassword: postgres
    postgresUser: postgres
    servicePort: 5432
    ownershipProcessor: indexer-polygon-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/polygon-mainnet
    startingBlockOwnership: "59689828"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerPolygonRpcEndpoint"
    laosProcessor: indexer-laos-processor-polygon
    apiProcessor: indexer-laos-polygon-api
    host: testnet.polygon-indexer.laosnetwork.io
    gqlPort: 4000
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken" 
    indexerLaosRpcEndpointSecretKey: "indexerLaosSigmaRpcEndpointForPolygon"
    laosGlobalConsensus: "0:0x77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f"
    laosParachain: "4006"
    laosPalletInstance: "51"
    indexerOwnershipParseTraces: "false" 
    installed: "true"
  - dbPodName: indexer-db-ethereum
    postgresDb: squid-ethereum
    postgresPassword: postgres
    postgresUser: postgres
    servicePort: 5432
    ownershipProcessor: indexer-ethereum-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/ethereum-mainnet
    startingBlockOwnership: "20365510"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerEthereumRpcEndpoint"
    laosProcessor: indexer-laos-processor-ethereum
    apiProcessor: indexer-laos-ethereum-api
    host: testnet.ethereum-indexer.laosnetwork.io
    gqlPort: 4000
    # maxBatchCallSizeOwnership: 200
    # rpcRateLimitOwnership: 10
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken" 
    indexerLaosRpcEndpointSecretKey: "indexerLaosSigmaRpcEndpointForEthereum"
    laosGlobalConsensus: "0:0x77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f"
    laosParachain: "4006"
    laosPalletInstance: "51"
    indexerOwnershipParseTraces: "false" 
    installed: "true"
  - dbPodName: indexer-db-hedera-testnet
    postgresDb: squid-hedera
    postgresPassword: postgres
    postgresUser: postgres
    servicePort: 5432
    ownershipProcessor: indexer-hedera-testnet-processor
    startingBlockOwnership: "12600100"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerHederaTestnetRpcEndpoint"
    laosProcessor: indexer-laos-processor-hedera-testnet
    apiProcessor: indexer-laos-hedera-testnet-api
    host: testnet.hedera-testnet-indexer.laosnetwork.io
    gqlPort: 4000
    # maxBatchCallSizeOwnership: 100
    # rpcRateLimitOwnership: 10
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken" 
    indexerLaosRpcEndpointSecretKey: "indexerLaosSigmaRpcEndpointForHederaTestnet"
    laosGlobalConsensus: "0:0x77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f"
    laosParachain: "4006"
    laosPalletInstance: "51"
    indexerOwnershipParseTraces: "false" 
    installed: "true"
laosNodesInstances:
  - name: public-node-protostar
    nodeVersion: "v0.25.0"
    chain: "laos-sigma"
    nginxServiceUrl: http://public-node-protostar.protostar.svc.cluster.local:9944
    installed: true
  - name: public-node-protostar-2
    nodeVersion: "v0.25.0"
    chain: "laos-sigma"
    nginxServiceUrl: http://public-node-protostar-2.protostar.svc.cluster.local:9944
    installed: true
  - name: laos-node-protostar
    nodeVersion: "v0.25.0"
    chain: "laos"
    setDnsPolicy: true
    nginxServiceUrl: http://laos-node-protostar.protostar.svc.cluster.local:9944
    installed: false
  - name: laos-node-protostar-1
    nodeVersion: "v0.25.0"
    chain: "laos"
    setDnsPolicy: true
    nginxServiceUrl: http://laos-node-protostar-1.protostar.svc.cluster.local:9944
    installed: false
  - name: laos-node-protostar-2
    nodeVersion: "v0.25.0"
    chain: "laos"
    setDnsPolicy: true
    nginxServiceUrl: http://laos-node-protostar-2.protostar.svc.cluster.local:9944
    installed: false
