namespace: indexers
laosIndexerInstances:
  - chainName: laos-sigma
    indexerName: indexer-laos-sigma
    postgresDb: indexerdb
    postgresPasswordSecretKey: indexerPostgresPassword
    postgresUser: indexer
    postgresHost: "stg-db-do-user-4813238-0.j.db.ondigitalocean.com"
    postgresPort: 25060
    startingBlock: "1"
    rpcEndpointSecretKey: "indexerLaosSigmaRpcEndpointForPolygon"
    rpcRateLimit: 10
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken"
    installed: "true"
ownershipIndexerInstances:
  - postgresDb: indexerdb
    postgresPasswordSecretKey: indexerPostgresPassword
    postgresUser: indexer
    postgresHost: "stg-db-do-user-4813238-0.j.db.ondigitalocean.com" 
    postgresPort: 25060
    chainName: Polygon
    chainId: "137"
    indexerName: indexer-polygon-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/polygon-mainnet
    startingBlock: "59689828"
    rpcEndpointSecretKey: "indexerPolygonRpcEndpoint"
    # rpcRateLimit: 10
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken" 
    laosGlobalConsensus: "0:0x77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f"
    laosParachain: "4006"
    laosPalletInstance: "51"
    indexerParseTraces: "false" 
    installed: "true"
  - postgresDb: indexerdb
    postgresPasswordSecretKey: indexerPostgresPassword
    postgresUser: indexer
    postgresPort: 25060
    chainName: Ethereum
    chainId: "1"
    indexerName: indexer-ethereum-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/ethereum-mainnet
    startingBlock: "20365510"
    rpcEndpointSecretKey: "indexerEthereumRpcEndpoint"
    # rpcRateLimit: 10
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken" 
    laosGlobalConsensus: "0:0x77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f"
    laosParachain: "4006"
    laosPalletInstance: "51"
    indexerParseTraces: "false" 
    installed: "true"
  - postgresDb: squid-hedera
    postgresPasswordSecretKey: indexerPostgresPassword
    postgresUser: indexer
    postgresPort: 25060
    chainName: Hedera
    chainId: "296"
    indexerName: indexer-hedera-testnet-processor
    startingBlock: "12600100"
    rpcEndpointSecretKey: "indexerHederaTestnetRpcEndpoint"
    # rpcRateLimit: 10
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken" 
    laosGlobalConsensus: "0:0x77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f"
    laosParachain: "4006"
    laosPalletInstance: "51"
    indexerParseTraces: "false" 
    installed: "true"
laosNodesInstances:
  - name: public-node-protostar
    nodeVersion: "v0.25.0"
    chain: "laos-sigma"
    nginxServiceUrl: http://public-node-protostar.indexers.svc.cluster.local:9944
    installed: true
  - name: public-node-protostar-2
    nodeVersion: "v0.25.0"
    chain: "laos-sigma"
    nginxServiceUrl: http://public-node-protostar-2.indexers.svc.cluster.local:9944
    installed: false
  - name: laos-node-protostar
    nodeVersion: "v0.25.0"
    chain: "laos"
    setDnsPolicy: true
    nginxServiceUrl: http://laos-node-protostar.indexers.svc.cluster.local:9944
    installed: false
  - name: laos-node-protostar-1
    nodeVersion: "v0.25.0"
    chain: "laos"
    setDnsPolicy: true
    nginxServiceUrl: http://laos-node-protostar-1.indexers.svc.cluster.local:9944
    installed: false
  - name: laos-node-protostar-2
    nodeVersion: "v0.25.0"
    chain: "laos"
    setDnsPolicy: true
    nginxServiceUrl: http://laos-node-protostar-2.indexers.svc.cluster.local:9944
    installed: false
