namespace: protostar
rpcLaos: wss://rpc.laossigma.laosfoundation.io
indexerInstances:
  - dbPodName: indexer-db-polygon
    postgresDb: squid
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-1
    servicePort: 5432
    containerPort: 5432
    mountPath: /var/lib/postgresql/pvdata
    mountName: indexer-pvc
    ownershipProcessor: indexer-polygon-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/polygon-mainnet
    startingBlockOwnership: "65270190"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerPolygonRpcEndpoint"
    laosProcessor: indexer-laos-processor-polygon
    apiProcessor: indexer-laos-polygon-api
    host: indexer.gorengine.com
    gqlPort: 4000
    # rpcRateLimitOwnership: 10
    # maxBatchCallSizeOwnership: 300
    # rpcRateLimit: 15
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken"
    indexerLaosRpcEndpointSecretKey: "indexerLaosRpcEndpointForPolygon"
    laosGlobalConsensus: "2"
    laosParachain: "3370"
    laosPalletInstance: "51"
    indexerOwnershipParseTraces: "false"
    installed: "true"
  - dbPodName: indexer-db-ethereum
    postgresDb: squid-ethereum
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-ethereum-1
    servicePort: 5432
    containerPort: 5433
    mountPath: /var/lib/postgresql/pvdata2
    mountName: indexer-pvc-ethereum
    ownershipProcessor: indexer-ethereum-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/ethereum-mainnet
    startingBlockOwnership: "21364679"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerEthereumRpcEndpoint"
    laosProcessor: indexer-laos-processor-ethereum
    apiProcessor: indexer-laos-ethereum-api
    host: indexer-ethereum.gorengine.com
    gqlPort: 4000
    # rpcRateLimitOwnership: 10
    # maxBatchCallSizeOwnership: 100
    # rpcRateLimit: 15
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken"
    indexerLaosRpcEndpointSecretKey: "indexerLaosRpcEndpointForEthereum"
    laosGlobalConsensus: "2"
    laosParachain: "3370"
    laosPalletInstance: "51"
    indexerOwnershipParseTraces: "false"
    installed: "true"
  - dbPodName: indexer-db-hedera
    postgresDb: squid-hedera
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-hedera
    servicePort: 5432
    containerPort: 5434
    mountPath: /var/lib/postgresql/pvdata3
    mountName: indexer-pvc-hedera
    ownershipProcessor: indexer-hedera-processor
    startingBlockOwnership: "12861134"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerHederaRpcEndpoint"
    laosProcessor: indexer-laos-processor-hedera
    apiProcessor: indexer-laos-hedera-api
    host: laos-mainnet.hedera-testnet-indexer.gorengine.com
    gqlPort: 4000
    # maxBatchCallSizeOwnership: 100
    # rpcRateLimitOwnership: 10
    rpcRateLimit: 15
    pinataGatewayApiTokenSecretKey: "pinataGatewayApiToken" 
    indexerLaosRpcEndpointSecretKey: "indexerLaosRpcEndpointForHedera"
    laosGlobalConsensus: "2"
    laosParachain: "3370"
    laosPalletInstance: "51"
    indexerOwnershipParseTraces: "false"
    installed: "true"
laosNodesInstances:
  - name: public-node-protostar
    nodeVersion: "v0.24.0"
    chain: "laos-sigma"
    nginxServiceUrl: http://public-node-protostar.protostar.svc.cluster.local:9944
    installed: true
  - name: laos-node-protostar
    nodeVersion: "v0.24.0"
    chain: "laos"
    setDnsPolicy: true
    nginxServiceUrl: http://laos-node-protostar.protostar.svc.cluster.local:9944
    installed: true
  - name: laos-node-protostar-2
    nodeVersion: "v0.24.0"
    chain: "laos"
    nginxServiceUrl: http://laos-node-protostar-2.protostar.svc.cluster.local:9944
    installed: true
  - name: laos-node-protostar-3
    nodeVersion: "v0.24.0"
    chain: "laos"
    nginxServiceUrl: http://laos-node-protostar-3.protostar.svc.cluster.local:9944
    installed: false
