apiVersion: apps/v1
kind: Deployment
metadata:
  name: laos-extentions
  labels:
    app.kubernetes.io/app: laos-extentions
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: laos-extentions
  template:
    metadata:
      labels:
        app.kubernetes.io/app: laos-extentions
    spec:
      containers:
        - name: laos-extentions
          image: freeverseio/laos-extentions:{{ .Values.imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '256Mi'
              cpu: '1'
            limits:
              memory: '512Mi'
              cpu: '2'
          env:  
            - name: GRAPHQL_ENDPOINT
              value: "http://laos-api-gateway.protostar.svc.cluster.local:4000/graphql"
          ports:
            - containerPort: 3000
      volumes:
        - name: db-certificate
          secret:
            secretName: db-cert