releases:
  - name: {{ .Values.name }}-release
    namespace: '{{ .Values.namespace }}'
    createNamespace: false
    installed: {{ .Values.installed }}
    chart: .
    wait: true
    values:
      - name: {{ .Values.name }}
      - imageTag: {{ .Values.imageTag }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresDbHost: {{ .Values.postgresDbHost }}
      - postgresPasswordSecretKey: {{ .Values.postgresPasswordSecretKey }}
      - postgresUser: {{ .Values.postgresUser }}
      - postgresPort: {{ .Values.postgresPort }}
      {{- if hasKey .Values "gatewayEndpoint" }}
      - gatewayEndpoint: {{ .Values.gatewayEndpoint }}
      {{- end }}
      - rpcEndpointSecretKey: {{ .Values.rpcEndpointSecretKey }}
      - laosGlobalConsensus: {{ .Values.laosGlobalConsensus }}
      - laosParachain: {{ .Values.laosParachain }}
      - laosPalletInstance: {{ .Values.laosPalletInstance }}
      - startingBlock: {{ .Values.startingBlock }}
      - command: {{ .Values.command }}
      {{- if hasKey .Values "indexerOwnershipParseTraces" }}
      - indexerOwnershipParseTraces: {{ .Values.indexerOwnershipParseTraces }}   
      {{- end }}
      {{- if hasKey .Values "rpcRateLimit" }}
      - rpcRateLimit: {{ .Values.rpcRateLimit }}
      {{- end }}
      {{- if hasKey .Values "maxBatchCallSizeOwnership" }}
      - maxBatchCallSizeOwnership: {{ .Values.maxBatchCallSizeOwnership }}
      {{- end }}
      {{- if hasKey .Values "pinataGatewayApiTokenSecretKey" }}
      - pinataGatewayApiTokenSecretKey: {{ .Values.pinataGatewayApiTokenSecretKey }}
      {{- end }}