releases:
  - name: {{ .Values.name }}-release
    namespace: '{{ .Values.namespace }}'
    createNamespace: false
    chart: .
    values:
      - name: {{ .Values.name }}  
      - nginxServiceUrl: {{ .Values.nginxServiceUrl }}
