apiVersion: v1
kind: Service
metadata:
  name: laos-extensions
  labels:
    app.kubernetes.io/app: laos-extensions
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/app: laos-extensions
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: extensions
  
