apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  nginx.conf: |
    events {
      # Maximum number of simultaneous connections
      worker_connections 50;
    }

    http {
      limit_req_zone "global_key" zone=global:10m rate=40r/s;

      server {
        listen 80;

        limit_req zone=global burst=10;

        location / {
          # Forward requests to the internal service
          proxy_pass {{ .Values.nginxServiceUrl }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }
      }
    }
